services:
  - type: web
    name: thinkbot-backend
    runtime: python
    plan: free
    buildCommand: pip install -r bot_core/requirements.txt
    startCommand: python -m bot_core.api_server
    envVars:
      - key: PORT
        value: 10000